CREATE SCHEMA IF NOT EXISTS carepro;

-- Raw landing tables for dynamic fields
CREATE TABLE IF NOT EXISTS carepro.raw_events (
  topic TEXT NOT NULL,
  key_text TEXT,
  payload_json JSONB NOT NULL,
  event_ts TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Curated tables for Superset
-- Base columns (exactly your source list)
CREATE TABLE IF NOT EXISTS carepro.art_cohort (
  id                       SERIAL NOT NULL,
  patientid                TEXT NOT NULL,
  art_number               TEXT,
  artnumber                TEXT,
  nupn                     TEXT,
  nrc                      TEXT,
  owningguid               TEXT,
  biometrics               TEXT,
  firstname                TEXT,
  surname                  TEXT,
  dob                      DATE,
  age                      INT,
  maritalstatus            TEXT,
  sex                      TEXT,
  occupation               TEXT,
  educational_level        TEXT,
  facilityname             TEXT,
  facilityid               TEXT,
  facilitymastercode       TEXT,
  currentpatientweight     NUMERIC,
  baselinepatientweight    NUMERIC,
  currentpatientheight     NUMERIC,
  baselinepatientheight    NUMERIC,
  district                 TEXT,
  province                 TEXT,
  hivtestdate              DATE,
  hivtestresults           TEXT,
  whostagingbaseline       TEXT,
  whostagingbaselinedate   DATE,
  whostagingcurrent        TEXT,
  whostagingcurrentdate    DATE,
  artstartdate             DATE,
  artregimenbaseline       TEXT,
  currentartregimen        TEXT,
  dispensationduration     NUMERIC,
  currentartregimendispensationdate DATE,
  baseline_cd4             NUMERIC,
  baselinecd4countdate     DATE,
  current_cd4              NUMERIC,
  currentcd4countdate      DATE,
  baseline_cd4_perc        NUMERIC,
  baselinecd4percdate      DATE,
  current_cd4_perc         NUMERIC,
  currentcd4percdate       DATE,
  baseline_vl_copies       NUMERIC,
  baselinevldate           DATE,
  current_vl_copies        NUMERIC,
  currentvldate            DATE,
  patientstatus            TEXT,
  patientstatusdate        DATE,
  ancvisitdate             DATE,
  estimateddateofdelivery  DATE,
  lastinteractionservice   TEXT,
  firstinteractionservice  TEXT,
  firstinteraction_date    DATE,
  lastinteraction_date     DATE,
  nextappointmentdate      DATE,
  prescription             TEXT,
  prescription_date        DATE,
  dsd                      TEXT,
  entrypoint               TEXT,
  discordantcouple         TEXT,
  multipleconcurrentpartners TEXT,
  previousfacilityname     TEXT,
  transferindate           DATE,
  codeofpreviousfacility   TEXT,
  facilitynametransferredto TEXT,
  codeoffacilitytransferredto TEXT,
  proteinuria              TEXT,
  proteinuriadate          DATE,
  rprrst                   TEXT,
  rprrsdate                DATE,
  hb                       NUMERIC,
  hbdate                   DATE,
  alt                      NUMERIC,
  altdate                  DATE,
  rbs                      NUMERIC,
  rbsdate                  DATE,
  creatinine               NUMERIC,
  creatininedate           DATE,
  hepatitisb               TEXT,
  hepatitisbdate           DATE,
  meningitis               TEXT,
  meningitisdate           DATE,
  csf                      TEXT,
  csfdate                  DATE,
  malaria                  TEXT,
  malariadate              DATE,
  geneexpertmtb            TEXT,
  geneexpertmtbdate        DATE,
  syphilisrdt              TEXT,
  syphilisrdtdate          DATE,
  tpha                     TEXT,
  tphardtdate              DATE,
  hpv                      TEXT,
  hpvdate                  DATE,
  tptplan                  TEXT,
  onantitb                 TEXT,
  currentlyhavetb          TEXT,
  kindoftb                 TEXT,
  wasattcompleted          TEXT,
  attnotcompletedreason    TEXT,
  isontpt                  TEXT,
  tptstartdate             DATE,
  tptenddate               DATE,
  istakentptthreeyears     TEXT,
  ispatienteligible        TEXT,
  reasonnotstarted         TEXT,
  dateeligiblefortpt       DATE,
  treatmentoutcome         TEXT,
  currentbmi               NUMERIC,
  baselinebmi              NUMERIC,
  currentmuac              NUMERIC,
  baselinemuac             NUMERIC,
  currentsystolic          NUMERIC,
  baselinesystolic         NUMERIC,
  currentdiastolic         NUMERIC,
  currentdiastolic_2       NUMERIC,
  currenttemperature       NUMERIC,
  baselinetemperature      NUMERIC,
  currentpulse             NUMERIC,
  baselinepulse            NUMERIC,
  currentheadcircumference NUMERIC,
  baselineheadcircumference NUMERIC,
  current_vitalsdate       DATE,
  baseline_vitalsdate      DATE,
  dateofdeath              DATE,
  placeofdeath             TEXT,
  causeofdeath             TEXT,
  causeofdeathanatomicaxisid TEXT,
  causeofdeathicpc2id      TEXT,
  causeofdeathpathologyaxisid TEXT,

  -- ===== Extra Stata-style derived fields =====
  on_art                   BOOLEAN,
  curr_regimen_based       TEXT,
  linkage_period_days      INT,
  linkage_period_mo        INT,
  linkagetocare_cat        TEXT,
  artclient_cohortmo       INT,
  art_cohort               TEXT,
  vl_baseline_cat          TEXT,
  mmd_type                 TEXT,
  dsd_model_f              TEXT,
  ahd                      BOOLEAN,
  vl_eligibility           BOOLEAN,
  vl_coverage_12m          BOOLEAN,
  vl_coverage_48m          BOOLEAN,
  outcome_1                TEXT,
  silent_transfer          BOOLEAN,
  re_initiated             BOOLEAN,

  PRIMARY KEY (patientid)
);

CREATE TABLE IF NOT EXISTS carepro.carepro_all_interactions (
  client_id TEXT,
  encounter_id TEXT,
  interaction_date DATE,
  service_name TEXT,
  service_category TEXT,
  facility_name TEXT,
  district TEXT,
  province TEXT,
  interaction_month INT,
  interaction_year INT,
  extras JSONB DEFAULT '{}'::jsonb,
  PRIMARY KEY (client_id, encounter_id)
);